# You've seen properties as things link hibernate.connection.url
# server.port=
# server.servlet.context-path=
server:
  port: 8080
  servlet:
    context-path: /
# in a properties file, it would look like spring.application.name
spring:
  application:
  datasource:

    driver-class-name: org.postgresql.Driver
    # url: jdbc:postgresql://employdb.c5a1xliscqxz.us-east-2.rds.amazonaws.com
    # url: jdbc:postgresql://localhost:5432/postgres?currentSchema=employdb
    # employdb.cnf0jeg0rmay.us-east-1.rds.amazonaws.com
    # url: jdbc:postgresql://localhost:5432/coffeeproduction_db/employdb
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=employeedb

    # url: jdbc:postgresql://localhost
    username: postgres
    password: Myv1ct0ry
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
     ddl-auto:
#      create-drop

# Default actuator gives us the health endpoint, we will add a few others
# Default actuator gives us the health endpoint, we will add a few others
management:
  endpoints:
    web:
      exposure:
        includes:
          - "beans"
          - "health"
          - "info"

